pipeline:
  name: cd-deploy-pipeline
  identifier: cddeploypipeline
  projectIdentifier: Assessment
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: deploy
        identifier: deploy
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: deploy
            serviceInputs:
              serviceDefinition:
                type: Kubernetes
                spec:
                  artifacts:
                    primary:
                      primaryArtifactRef: <+input>
                      sources: <+input>
            gitBranch: main
          environment:
            environmentRef: Dev
            deployToAll: false
            infrastructureDefinitions:
              - identifier: devk8s
          execution:
            steps:
              - stepGroup:
                  name: Canary Deployment
                  identifier: canaryDeployment
                  steps:
                    - step:
                        name: Rollout Deployment
                        identifier: rolloutDeployment_canary
                        type: K8sRollingDeploy
                        timeout: 10m
                        spec:
                          skipDryRun: false
                  rollbackSteps:
                    - step:
                        name: Rollback Deployment
                        identifier: rollbackDeployment_canary
                        type: K8sRollingRollback
                        timeout: 10m
                        spec: {}
              - stepGroup:
                  name: Primary Deployment
                  identifier: primaryDeployment
                  steps:
                    - step:
                        name: Rollout Deployment
                        identifier: rolloutDeployment_primary
                        type: K8sRollingDeploy
                        timeout: 10m
                        spec:
                          skipDryRun: false
                    - step:
                        name: Finalize Deployment
                        identifier: finalizeDeployment
                        type: K8sCanaryDelete
                        timeout: 10m
                        spec: {}
                  rollbackSteps:
                    - step:
                        name: Rollback Deployment
                        identifier: rollbackDeployment_primary
                        type: K8sRollingRollback
                        timeout: 10m
                        spec: {}
            rollbackSteps:
              - step:
                  name: Rolling Rollback
                  identifier: rollingRollback
                  type: K8sRollingRollback
                  timeout: 10m
                  spec: {}
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
